apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: ghcr.io/camptocamp/course_docker_backend:python
        name: course-docker-backend-qthcz
        resources: {}
        ports:
          - containerPort: 8080
            name: http
