global:
  scrape_interval: 5s
  scrape_timeout: 4s
  evaluation_interval: 1m
scrape_configs:
- job_name: python-backend
  static_configs:
  - targets:
    - python-backend:8080
- job_name: go-backend
  static_configs:
  - targets:
    - go-backend:8080
- job_name: java-backend
  metrics_path: /actuator/prometheus
  static_configs:
  - targets:
    - java-backend:8080
