FROM python:3
WORKDIR /usr/src/app/

# install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get update && \
    apt-get -y install binutils curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    pip install --no-cache-dir debugpy

# Inject code
COPY api.py .
COPY data.json /etc/backend/data.json

EXPOSE 8080 5678
ENTRYPOINT ["python", "-Xfrozen_modules=off", "-m", "debugpy", "--listen", "0.0.0.0:5678"]
CMD ["api.py"]
