ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: containers-course-app.jacroute.apps.campto.camp
      paths:
        - /
  tls:
    - secretName: containers-course-app
      hosts:
        - containers-course-app.jacroute.apps.campto.camp
